project:
  type: website
  output-dir: _site # folder where all rendered files (for preview) are saved to
  render:
    - "*.qmd"
    - "!x_not_published/" # do not render / ignore this folder

website:
  title: "Sereina"
  favicon: home_polygon_1.png # image in root folder, same for "home" page
  search:
    location: navbar
    type: overlay
  page-footer: 
        background: "#f8f8f6"
        center: © 2024  &middot; Made with [![](https://www.r-project.org/Rlogo.png){fig-alt="R" width=25px}](https://www.r-project.org/)  and [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
  navbar:
    title: false # not using website title on left side of navbar...
    search: true
    logo: home_polygon_1.png # logo on top left, next to website title
    right:
      - href: index.qmd
        text: home
      - href: about/about.qmd
        text: about
      - text: publications
        aria-label: "Publications"
        href: publications/index.qmd
      - href: talks/index.qmd
        text: talks
        aria-label: "Talks"
      - href: blog/index.qmd
        text: blog
      - icon: github
        href: https://github.com/serigra/Webpage_Quarto
    
format:
  html:
    theme: cosmo
    backgroundcolor: "#f8f8f6"
    css: styles.css
    toc: true
    grid: # to format layout of "HOME" Site, formating of other sites is defined in styles_publications.css, styles_talks.css, etc
      sidebar-width: 180px
      body-width: 1100px
      margin-width: 200px
      gutter-width: 1.5rem

editor: source

  
