<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sereina M. Graber">
<meta name="dcterms.date" content="2024-09-16">

<title>Unravelling Marginal Effects – Sereina</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../home_polygon_1.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="../styles_blog_individual.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../home_polygon_1.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sereina M. Graber</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about/about.html"> 
<span class="menu-text">about</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications/index.html"> 
<span class="menu-text">publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../talks/index.html"> 
<span class="menu-text">talks</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog/index.html"> 
<span class="menu-text">blog</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/serigra/Webpage_Quarto"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#unraveling-curved-relationships-marginal-effects-between-continuous-variables" id="toc-unraveling-curved-relationships-marginal-effects-between-continuous-variables" class="nav-link active" data-scroll-target="#unraveling-curved-relationships-marginal-effects-between-continuous-variables">Unraveling Curved Relationships: Marginal Effects Between Continuous Variables</a></li>
  <li><a href="#unravelling-logistic-regression-and-marginal-effects" id="toc-unravelling-logistic-regression-and-marginal-effects" class="nav-link" data-scroll-target="#unravelling-logistic-regression-and-marginal-effects">Unravelling Logistic Regression and Marginal Effects</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Unravelling Marginal Effects</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sereina M. Graber </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 16, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><br><br></p>
<p>Raw parameter estimates from complex models, particularly those involving non-linear terms or interactions, are often challenging to interpret and may lack real-world context. This difficulty is especially pronounced for non-statisticians, who are often the ones tasked with translating results into practical solutions. In this regard, marginal effects can be useful, as they provide a clearer and more interpretable view of the relationships within a statistical model.<br>
The term “marginal effects” carries slightly different meanings across different fields and contexts. For an in-depth exploration of this terminology, I recommend to read <a href="https://www.andrewheiss.com/blog/2022/05/20/marginalia/">Andrew Heiss’s blog post</a>. For the following, I’ll adhere to the following general concept: Marginal effects illustrate how a one-unit change in the independent variable influences the dependent variable, while holding other factors or covariates constant. This concept manifests differently across model types:</p>
<ul>
<li><strong>Linear Regression Models</strong>: Here, coefficients themselves already represent (constant) marginal effects, due to the linear nature of the relationship. For instance, in a model predicting salary based on years of experience, a coefficient of 500 for experience indicates that each additional year increases salary by 500 units.</li>
<li><strong>Non-linear Models</strong>: In models such as logit, probit, Poisson, or those involving quadratic/ polynomial terms, marginal effects are not constant. They must be calculated for specific values of the independent variable. For example, in a logistic regression model predicting diabetes based on glucose levels, the marginal effect represents the change in the probability of diabetes occurring for a one-unit change in glucose level. It’s worth noting that in such models, the regression coefficient itself represents the log odds ratio rather than the change in actual probability.</li>
</ul>
<p>In the following sections, I’ll explore two examples of how to enhance the interpretability of model outputs using marginal effects and the <a href="https://marginaleffects.com/"><code>marginaleffects</code></a> package.</p>
<p><em>Note I</em>: While researching marginal effects, I found two particularly insightful blog posts - one by an unnamed author from the <a href="https://library.virginia.edu/data/articles/a-beginners-guide-to-marginal-effects">University of Virginia</a> and another by <a href="https://www.andrewheiss.com/blog/2022/05/20/marginalia/">Andrew Heiss</a>. Both offer comprehensive descriptions of the concept. However, in this post, I’ve attempted to articulate the idea behind marginal effects in my own words, hoping to provide a perspective that might be helpful to others, including my future self.</p>
<p><em>Note II</em>: There are several other excellent <code>R</code> packages for calculating marginal effects, such as <a href="https://cran.r-project.org/web/packages/margins/index.html"><code>margins</code></a> and <a href="https://cran.r-project.org/web/packages/emmeans/index.html"><code>emmeans</code></a>. However, for the sake of simplicity and consistency, I chose not to include them in this post.</p>
<div class="tiny-code">

</div>
<p><br><br></p>
<section id="unraveling-curved-relationships-marginal-effects-between-continuous-variables" class="level2">
<h2 class="anchored" data-anchor-id="unraveling-curved-relationships-marginal-effects-between-continuous-variables">Unraveling Curved Relationships: Marginal Effects Between Continuous Variables</h2>
<p>When dealing with continuous variables for both predictors and outcomes, marginal effects become a powerful tool for interpretation of non-linear models like quadratic relationships, where raw regression estimates are challenging to interpret. Let’s explore this concept using a synthetic data set on plant growth and fertilizer. The data follows a natural inverted U-shaped curve that’s commonly observed in agriculture: plants respond positively to fertilizer up to an optimal point (around 3 g/m²), after which excess nutrients become toxic and inhibit growth, demonstrating a classic quadratic relationship.</p>
<p>Data set</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="at">length.out =</span> <span class="dv">100</span>)           <span class="co"># Fertilizer amount</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">10</span><span class="sc">*</span>x <span class="sc">+</span> <span class="dv">5</span> <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">10</span>)  <span class="co"># Plant growth</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>plant_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">fertilizer =</span> x, <span class="at">growth =</span> y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="medium-space">

</div>
<section id="linear-vs.-quadratic-which-fits-better" class="level3">
<h3 class="anchored" data-anchor-id="linear-vs.-quadratic-which-fits-better">Linear vs.&nbsp;Quadratic: Which Fits Better?</h3>
<p>First, let’s compare a linear and a quadratic model to see which better describes the data:</p>
<div class="tiny-code">
<details class="code-fold">
<summary>R Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plant_data, <span class="fu">aes</span>(<span class="at">x =</span> fertilizer, <span class="at">y =</span> growth) ) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">'black'</span>, <span class="at">fill =</span> <span class="st">'#7950f2'</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>,  <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">'#1e1e1e'</span>) <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">'Linear Model'</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"Fertilizer [g/"</span>, m<span class="sc">^</span><span class="dv">2</span>, <span class="st">']'</span>)), <span class="at">y =</span> <span class="st">"Growth [cm]"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># linear model</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>linear_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(growth <span class="sc">~</span> fertilizer, <span class="at">data =</span> plant_data)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linear_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell quarto-layout-panel" data-layout="[[80,20]]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 80.0%;justify-content: center;">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="552"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 20.0%;justify-content: flex-start;">
<pre><code>
Call:
lm(formula = growth ~ fertilizer, data = plant_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-45.408 -10.298  -1.008  13.436  37.090 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  37.6577     3.3830   11.13   &lt;2e-16 ***
fertilizer   -9.7514     0.5845  -16.68   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.04 on 98 degrees of freedom
Multiple R-squared:  0.7396,    Adjusted R-squared:  0.7369 
F-statistic: 278.4 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div>
</div>
<div class="tiny-code">
<details class="code-fold">
<summary>R Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plant_data, <span class="fu">aes</span>(<span class="at">x =</span> fertilizer, <span class="at">y =</span> growth) ) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">fill =</span> <span class="st">'#7950f2'</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>,  <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>), <span class="at">linewidth =</span> <span class="fl">1.3</span>, <span class="at">color =</span> <span class="st">'#1e1e1e'</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">'Quadratic Model'</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"Fertilizer [g/"</span>, m<span class="sc">^</span><span class="dv">2</span>, <span class="st">']'</span>)), <span class="at">y =</span> <span class="st">"Growth [cm]"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># quadratic model</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>quadratic_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(growth <span class="sc">~</span> fertilizer <span class="sc">+</span>  <span class="fu">I</span>(fertilizer<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> plant_data)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(quadratic_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell quarto-layout-panel" data-layout="[[80,20]]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 80.0%;justify-content: center;">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="576"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 20.0%;justify-content: flex-start;">
<pre><code>
Call:
lm(formula = growth ~ fertilizer + I(fertilizer^2), data = plant_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-24.0680  -5.9884  -0.2665   6.7743  21.9457 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       6.6991     2.6889   2.491   0.0144 *  
fertilizer        9.0133     1.2427   7.253    1e-10 ***
I(fertilizer^2)  -1.8765     0.1203 -15.604   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.143 on 97 degrees of freedom
Multiple R-squared:  0.9258,    Adjusted R-squared:  0.9243 
F-statistic: 605.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div>
</div>
<p>The quadratic model shows a much smaller residual deviance, indicating a better fit to the data, which is not very surprising. This suggests a more complex relationship between fertilizer and plant growth: growth tends to increase with the amount of fertilizer until around 3 g/m², after which it begins to decrease again.</p>
<p><br><br></p>
</section>
<section id="interpreting-quadratic-relationships-the-power-of-marginal-effects" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-quadratic-relationships-the-power-of-marginal-effects">Interpreting Quadratic Relationships: The Power of Marginal Effects</h3>
<p>Interpreting the coefficients of a quadratic model can be challenging - so we have two coefficients <code>fertilizer</code> and <code>I(fertilizer^2)</code>, one negative one positive - but how to interpret them? This is where marginal effects, specifically <em>Marginal Effects at Representative Values (MER)</em>, come into play. We can calculate the slope (or tangent) at different amounts of fertilizer to better understand the relationship, and these slopes are nothing else than <em>marginal effects</em>. Let’s calculate the marginal effects at 2 g/m² and 6 g/m² using the <code>slopes()</code> function from the <code>marginaleffects</code> package:</p>
<div class="small-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slopes</span>(quadratic_model, <span class="at">newdata =</span> <span class="fu">datagrid</span>(<span class="at">fertilizer =</span> <span class="fu">c</span>(<span class="fl">1.5</span>, <span class="dv">6</span>))) <span class="ot">-&gt;</span> s; s</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       Term fertilizer Estimate Std. Error      z Pr(&gt;|z|)     S  2.5 % 97.5 %
 fertilizer        1.5     3.38      0.898   3.77   &lt;0.001  12.6   1.62   5.14
 fertilizer        6.0   -13.50      0.395 -34.17   &lt;0.001 847.9 -14.28 -12.73

Type:  response 
Columns: rowid, term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, fertilizer, predicted_lo, predicted_hi, predicted, growth </code></pre>
</div>
</div>
</div>
<div class="medium-space">

</div>
<p>Now, let’s visualize these slopes on the plot from above (inspired by <a href="https://www.andrewheiss.com/blog/2022/05/20/marginalia/">Andrew Heiss</a>):</p>
<div class="small-code">
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>R Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># y = 6.6991 + 9.0133*x + -1.8765(x^2) </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>b_15 <span class="ot">&lt;-</span> s<span class="sc">$</span>estimate[<span class="dv">1</span>]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>x_15 <span class="ot">&lt;-</span> <span class="fl">1.5</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>y_15 <span class="ot">&lt;-</span> <span class="fl">6.6991</span> <span class="sc">+</span> <span class="fl">9.0133</span><span class="sc">*</span><span class="fl">1.5</span> <span class="sc">-</span><span class="fl">1.8765</span><span class="sc">*</span>(<span class="fl">1.5</span><span class="sc">^</span><span class="dv">2</span>) </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>intercept_15 <span class="ot">&lt;-</span> b_15 <span class="sc">*</span> (<span class="sc">-</span>x_15) <span class="sc">+</span> y_15</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>b_6 <span class="ot">&lt;-</span> s<span class="sc">$</span>estimate[<span class="dv">2</span>]</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>x_6 <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>y_6 <span class="ot">&lt;-</span> <span class="fl">6.6991</span> <span class="sc">+</span> <span class="fl">9.0133</span><span class="sc">*</span><span class="dv">6</span> <span class="sc">-</span><span class="fl">1.8765</span><span class="sc">*</span>(<span class="dv">6</span><span class="sc">^</span><span class="dv">2</span>) </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>intercept_6 <span class="ot">&lt;-</span> b_6 <span class="sc">*</span> (<span class="sc">-</span>x_6) <span class="sc">+</span> y_6</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>d.annot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">c</span>(x_15, x_6), </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>                      <span class="at">y =</span> <span class="fu">c</span>(y_15, y_6), </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>                      <span class="at">b =</span> <span class="fu">c</span>(b_15, b_6),</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>                      <span class="at">i =</span> <span class="fu">c</span>(intercept_15, intercept_6)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>                      ) <span class="sc">%&gt;%</span> </span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">'dy/dx = '</span> , <span class="fu">round</span>(b, <span class="dv">2</span>)))</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plant_data, <span class="fu">aes</span>(<span class="at">x =</span> fertilizer, <span class="at">y =</span> growth) ) <span class="sc">+</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">fill =</span> <span class="st">'#7950f2'</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>,  <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>), <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">'#1e1e1e'</span>) <span class="sc">+</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">data =</span> d.annot, <span class="fu">aes</span>(<span class="at">slope =</span> b, <span class="at">intercept =</span> i),</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>                <span class="at">linewidth =</span> <span class="fl">1.1</span>, <span class="at">color =</span> <span class="st">'darkorange'</span>) <span class="sc">+</span>  </span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_richtext</span>(<span class="at">data =</span> d.annot, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">label =</span> label), <span class="at">color =</span> <span class="st">'darkorange'</span>, <span class="at">nudge_y =</span> <span class="dv">7</span>) <span class="sc">+</span> </span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">data =</span> d.annot, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y), <span class="at">fill =</span> <span class="st">'darkorange'</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    <span class="co">#scale_x_continuous(breaks = seq(0, 90, by=10)) +</span></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    <span class="co">#scale_y_continuous(limits = c(0,70)) + </span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">'Marginal Effects at Representative Values (MER)'</span>,</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"Fertilizer [g/"</span>, m<span class="sc">^</span><span class="dv">2</span>, <span class="st">']'</span>)), <span class="at">y =</span> <span class="st">"Grwoth [cm]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
<p>This visualization helps to understand how the relationship between the amount of fertilizer and growth changes. The slope is positive at the amount of 1.5 g/m² but negative at 6 g/m², indicating a clear shift in the relationship.</p>
<p><br><br></p>
</section>
<section id="comprehensive-view-marginal-effects-across-all-ages" class="level3">
<h3 class="anchored" data-anchor-id="comprehensive-view-marginal-effects-across-all-ages">Comprehensive View: Marginal Effects Across All Ages</h3>
<p>To get a complete picture, we can calculate and plot the marginal effects (slopes) for all amounts of fertilizer using the <code>plot_slopes()</code> function:</p>
<div class="small-code">
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>R Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_slopes</span>(quadratic_model, <span class="at">variables =</span> <span class="st">"fertilizer"</span>, <span class="at">condition =</span> <span class="st">"fertilizer"</span>) <span class="sc">+</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">'darkgrey'</span>, <span class="at">linetype =</span> <span class="st">'dotted'</span>, <span class="at">lwd =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_richtext</span>(<span class="at">data =</span> d.annot, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> b, <span class="at">label =</span> label), <span class="at">color =</span> <span class="st">'darkorange'</span>, <span class="at">nudge_y =</span> <span class="fl">3.5</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> d.annot, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> b), <span class="at">fill =</span> <span class="st">'darkorange'</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">'Marginal Effects Across All Amounts of Fertilizer'</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">'Marginal Effect (dy/dx)'</span>, <span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"Fertilizer [g/"</span>, m<span class="sc">^</span><span class="dv">2</span>, <span class="st">']'</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
<p><br><br></p>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>The analysis reveals that:</p>
<ul>
<li><p><strong>At 1.5 g/m² of fertilizer</strong>: A one-unit increase in fertilizer (from 1.5 to 2.5 g/m²) is associated with an estimated 3.38 cm increase in plant growth.</p></li>
<li><p><strong>At 6 g/m² of fertilizer</strong>: A one-unit increase in fertilizer (from 6 to 7 g/m²) is associated with an estimated 13.5 cm decrease in plant growth.</p></li>
</ul>
<p>This shift from a positive to a negative relationship when increasing the amount of fertilizer illustrates that at lower levels (before the optimum), additional fertilizer promotes growth, and at higher levels (after the optimum), additional fertilizer reduces growth due to toxicity.</p>
<p><br><br></p>
</section>
<section id="beyond-mer-exploring-mem-and-ame" class="level3">
<h3 class="anchored" data-anchor-id="beyond-mer-exploring-mem-and-ame">Beyond MER: Exploring MEM and AME</h3>
<p>We’ve just looked at the concept of <em>Marginal Effects at Representative Values (MER)</em>. But there’s more! Two other concepts can shed light on the data (depending on context and data, one or the other make more sense): MEM and AME. Let’s break these three down in more detail:</p>
<div class="columns">
<div class="column" style="width:55%;">
<p><br><br> <strong>Marginal Effect at Representative Values (MER)</strong>:</p>
<p>This represents the dy/dx at very specific, representative values of x (as for the amount of fertilizer of 2 g/m2 and 6 g/m2 above).</p>
<div class="tiny-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slopes</span>(quadratic_model, <span class="at">newdata =</span> <span class="fu">datagrid</span>(<span class="at">age =</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">60</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some of the variable names are missing from the model data: age</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 age Estimate Std. Error     z Pr(&gt;|z|)     S 2.5 % 97.5 %
  30    -9.75      0.314 -31.1   &lt;0.001 702.9 -10.4  -9.14
  60    -9.75      0.314 -31.1   &lt;0.001 702.9 -10.4  -9.14

Term: fertilizer
Type:  response 
Columns: rowid, term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, age, predicted_lo, predicted_hi, predicted, fertilizer, growth </code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><img src="images/MER_continuous.png" class="img-fluid" width="400"></p>
</div>
</div>
<div class="columns">
<div class="column" style="width:55%;">
<p><br><br></p>
<p><strong>Marginal Effect at the Mean (MEM)</strong>:</p>
<p>This represents the dy/dx at the mean value of x (amount of fertilizer in the example above).</p>
<div class="tiny-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slopes</span>(quadratic_model, <span class="at">newdata =</span> <span class="st">"mean"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error     z Pr(&gt;|z|)     S 2.5 % 97.5 %
    -9.75      0.314 -31.1   &lt;0.001 702.9 -10.4  -9.14

Term: fertilizer
Type:  response 
Columns: rowid, term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, fertilizer, growth </code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><img src="images/MEM_continuous.png" class="img-fluid" width="400"></p>
</div>
</div>
<div class="columns">
<div class="column" style="width:55%;">
<p><br><br> <strong>Average Marginal Effect (AME)</strong>:</p>
<p>This is the mean of all observation-specific marginal effects. It’s calculated by determining dy/dx at each value of x and then taking the average. Based on the example above, this might not be very helpful though.</p>
<div class="tiny-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(quadratic_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error     z Pr(&gt;|z|)     S 2.5 % 97.5 %
    -9.75      0.314 -31.1   &lt;0.001 702.9 -10.4  -9.14

Term: fertilizer
Type:  response 
Comparison: mean(dY/dX)
Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted </code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><img src="images/AME_continuous.png" class="img-fluid" width="400"></p>
</div>
</div>
<p><br><br></p>
</section>
</section>
<section id="unravelling-logistic-regression-and-marginal-effects" class="level2">
<h2 class="anchored" data-anchor-id="unravelling-logistic-regression-and-marginal-effects">Unravelling Logistic Regression and Marginal Effects</h2>
<p>Logistic regression is a powerful and often used tool. The raw parameters represent log odds ratios, expressed as <span class="math inline">\(log(\frac{p}{1-p})\)</span>. Exponentiating these coefficients results in odds ratios <span class="math inline">\(\frac{p}{1-p}\)</span>, which is a common measure used in scientific studies. But what do these really mean in practical terms? The interpretation can be tricky, and it’s easy to conflate odds with probabilities. While it would be convenient if they were the same, they’re not – and this is where marginal effects shine.</p>
<p>Let’s explore this concept using the <code>PimaIndiansDiabetes2</code> dataset again. We’ll investigate how age and above-average body mass (binary coded) relate to the risk of diabetes. Again, this example is simplified for illustration, and is simply used to provide insights into marginal effects in case of a binary coded outcome variable.</p>
<div class="small-space">

</div>
<p>First, let’s prepare our data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add binary predictor variable</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>PimaIndiansDiabetes2 <span class="sc">%&lt;&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(mass)) <span class="sc">%&gt;%</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diab =</span> <span class="fu">ifelse</span>(diabetes <span class="sc">==</span> <span class="st">'pos'</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">mass_fg =</span> <span class="fu">f_case_when</span>(mass <span class="sc">&lt;=</span> <span class="fu">mean</span>(mass) <span class="sc">~</span> <span class="st">'below-avg'</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                               mass <span class="sc">&gt;</span> <span class="fu">mean</span>(mass) <span class="sc">~</span> <span class="st">'above-avg'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="small-space">

</div>
<p>Lets build the model:</p>
<div class="teenytiny-code">
<details class="code-fold">
<summary>R Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot: age</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(PimaIndiansDiabetes2, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> diab)) <span class="sc">+</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">fill =</span> <span class="st">'#7950f2'</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>,  <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"glm"</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">se=</span><span class="cn">TRUE</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family=</span>binomial), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">'Logistic Regression - Age'</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">'Probability of Diabetes'</span>, <span class="at">x =</span> <span class="st">'Age'</span>) <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>))</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co"># plot: body mass binary coded</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(PimaIndiansDiabetes2, <span class="fu">aes</span>(<span class="at">x =</span> mass_fg, <span class="at">y =</span> diab)) <span class="sc">+</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.3</span>, <span class="at">height =</span> <span class="fl">0.05</span>, <span class="at">fill =</span> <span class="st">'#7950f2'</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>,  <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">"binomial"</span>), <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Body mass"</span>, <span class="at">y =</span> <span class="st">"Probability of Diabetes"</span>, <span class="at">title =</span> <span class="st">"Logistic Regression - Body Mass Flag"</span>) <span class="sc">+</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>),</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>))</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>p1<span class="sc">+</span>p2<span class="sc">+</span><span class="fu">plot_annotation</span>(<span class="at">theme =</span> <span class="fu">theme</span>(<span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span><span class="st">"#f8faf7"</span>, <span class="at">color=</span><span class="st">"#f8faf7"</span>)))</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="co"># logistic regression</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>logit_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> age <span class="sc">+</span> mass_fg, <span class="at">data =</span> PimaIndiansDiabetes2, <span class="at">family =</span> <span class="st">'binomial'</span>)</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell quarto-layout-panel" data-layout="[[80,20]]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 80.0%;justify-content: center;">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="768"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 20.0%;justify-content: flex-start;">
<pre><code>
Call:
glm(formula = diabetes ~ age + mass_fg, family = "binomial", 
    data = PimaIndiansDiabetes2)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      -2.568264   0.269092  -9.544  &lt; 2e-16 ***
age               0.041748   0.006804   6.136 8.46e-10 ***
mass_fgabove-avg  1.021895   0.162706   6.281 3.37e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 981.53  on 756  degrees of freedom
Residual deviance: 899.13  on 754  degrees of freedom
AIC: 905.13

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</div>
</div>
<p>Lets look at the odds ratios:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(logit_model<span class="sc">$</span>coefficients)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept)              age mass_fgabove-avg 
      0.07666854       1.04263177       2.77845620 </code></pre>
</div>
</div>
<p><br></p>
<p><strong>Traditional interpretation</strong>:</p>
<ul>
<li>For each year increase in age, the odds of having diabetes increase by 4%.</li>
<li>Individuals with above-average body mass have odds of diabetes 3 times higher than those with below-average body mass.</li>
</ul>
<p>While these interpretations are technically correct, they’re not very intuitive. Many people, including myself, find odds ratios difficult to grasp and often conflate them with probabilities.</p>
<p>Therefore lets look at marginal effects, which offer a more accessible way to interpret our results. They show how changes in our predictors affect the probability (not odds!) of the outcome. First thing we could do, is to get individual <em>risk differences</em>: predict the probability of diabetes for a given subject based on their current age, and the probability for one year older (+1), and calculate the difference between the two. Analogously for the binary variable, predict the probability of diabetes for each subject, once treating the subject to be above average massed, and once below averaged massed, and take the difference thereof. We could do this by hand, but the <code>comparisons()</code> function from the <code>marginaleffects</code> does this for us (which is the analogue function to <code>slopes()</code> for the continuous relationship from above).</p>
<div class="columns">
<div class="column" style="width:48.75%;">
<div class="tinyer-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">comparisons</span>(logit_model, <span class="at">variable =</span> <span class="st">'age'</span>) <span class="ot">-&gt;</span> rr.age; rr.age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error     z Pr(&gt;|z|)    S   2.5 %  97.5 %
  0.00965   0.001306  7.39   &lt;0.001 42.7 0.00709 0.01221
  0.00721   0.001180  6.12   &lt;0.001 29.9 0.00490 0.00953
  0.00738   0.001229  6.01   &lt;0.001 29.0 0.00497 0.00979
  0.00556   0.000720  7.72   &lt;0.001 46.3 0.00415 0.00698
  0.01038   0.001691  6.14   &lt;0.001 30.1 0.00706 0.01369
--- 747 rows omitted. See ?avg_comparisons and ?print.marginaleffects --- 
  0.00780   0.000640 12.20   &lt;0.001 111.3 0.00655 0.00906
  0.01003   0.001564  6.42   &lt;0.001  32.7 0.00697 0.01310
  0.00705   0.001130  6.23   &lt;0.001  31.0 0.00483 0.00926
  0.00959   0.001821  5.27   &lt;0.001  22.8 0.00602 0.01316
  0.00588   0.000803  7.32   &lt;0.001  41.9 0.00431 0.00746
Term: age
Type:  response 
Comparison: +1
Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, diabetes, age, mass_fg </code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:2.5%;">

</div><div class="column" style="width:48.75%;">
<div class="tinyer-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">comparisons</span>(logit_model, <span class="at">variable =</span> <span class="st">'mass_fg'</span>) <span class="ot">-&gt;</span> rr.mass; rr.mass</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error    z Pr(&gt;|z|)    S 2.5 % 97.5 %
    0.250     0.0381 6.55   &lt;0.001 34.1 0.175  0.325
    0.219     0.0336 6.51   &lt;0.001 33.6 0.153  0.285
    0.222     0.0340 6.52   &lt;0.001 33.7 0.155  0.289
    0.183     0.0297 6.16   &lt;0.001 30.4 0.125  0.241
    0.225     0.0344 6.53   &lt;0.001 33.8 0.157  0.292
--- 747 rows omitted. See ?avg_comparisons and ?print.marginaleffects --- 
    0.232     0.0379 6.12   &lt;0.001 30.0 0.158  0.306
    0.205     0.0320 6.42   &lt;0.001 32.8 0.143  0.268
    0.216     0.0332 6.49   &lt;0.001 33.4 0.150  0.281
    0.250     0.0380 6.56   &lt;0.001 34.1 0.175  0.324
    0.191     0.0304 6.27   &lt;0.001 31.4 0.131  0.250
Term: mass_fg
Type:  response 
Comparison: above-avg - below-avg
Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, diabetes, age, mass_fg </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="small-space">

</div>
<p>The outputs of the <code>comparisons()</code> function shows for each individual the difference in predicted probability of current age, and for one year older (+1), and the difference in probability treating the subject to be above average massed, vs.&nbsp;below averaged massed.</p>
<p><br></p>
<section id="average-marginal-effects-ame" class="level3">
<h3 class="anchored" data-anchor-id="average-marginal-effects-ame">Average Marginal Effects (AME)</h3>
<p>Furthermore, to get a population-level perspective, we can average these individual effects from above using <code>avg_comparisons()</code></p>
<div class="columns">
<div class="column" style="width:48.75%;">
<div class="tinyer-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_comparisons</span>(logit_model, <span class="at">variable =</span> <span class="st">'age'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error    z Pr(&gt;|z|)    S   2.5 % 97.5 %
  0.00854    0.00127 6.74   &lt;0.001 35.9 0.00606  0.011

Term: age
Type:  response 
Comparison: mean(+1)
Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted </code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:2.5%;">

</div><div class="column" style="width:48.75%;">
<div class="tinyer-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_comparisons</span>(logit_model, <span class="at">variable =</span> <span class="st">'mass_fg'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error   z Pr(&gt;|z|)    S 2.5 % 97.5 %
    0.215     0.0331 6.5   &lt;0.001 33.5  0.15   0.28

Term: mass_fg
Type:  response 
Comparison: mean(above-avg) - mean(below-avg)
Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="small-space">

</div>
<p>So what do these risk differences, or population averaged risk differences, tell us?</p>
<ul>
<li>On average, for each year increase in age, the probability of diabetes increases by 0.9 percentage points.</li>
<li>For changing from below-averaged body mass to above-averaged body mass increases the probability of diabetes, again on average across all subjects, by 23% percentage points.</li>
</ul>
<p><em>Note</em>: If you prefer risk ratios instead of risk differences, you can easily add the argument <code>comparison = "ratio"</code> to the <code>comparisons()</code> function.</p>
<p>These marginal effects provide a much more intuitive interpretation than the raw parameter estimates (log odds ratios). They show how changes in the independent variables (age and body mass group) influence the outcome probability of diabetes.</p>
<p>We can further refine our analysis by exploring <em>Marginal Effects at the Mean (MEA)</em> and <em>Marginal Effects at Representative Values (MER)</em>.</p>
<p><br></p>
</section>
<section id="marginal-effects-at-the-mean-mea" class="level3">
<h3 class="anchored" data-anchor-id="marginal-effects-at-the-mean-mea">Marginal Effects at the Mean (MEA)</h3>
<p>If we don’t specify the <code>variables</code> argument, the <code>comparisons()</code>-function calculates marginal effects at the means of both predictors:</p>
<div class="tiny-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">comparisons</span>(logit_model, <span class="at">newdata =</span> <span class="st">'mean'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Term              Contrast Estimate Std. Error    z Pr(&gt;|z|)    S   2.5 % 97.5 %  age   mass_fg
 age     +1                     0.00759    0.00129 5.88   &lt;0.001 27.8 0.00506 0.0101 33.3 below-avg
 mass_fg above-avg - below-avg  0.22558    0.03455 6.53   &lt;0.001 33.8 0.15787 0.2933 33.3 below-avg

Type:  response 
Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, age, mass_fg, diabetes </code></pre>
</div>
</div>
</div>
<div class="small-space">

</div>
<p>This gives us the marginal effects at the average age of 33.2 years and the more common body mass category (above-avg). We can verify this result manually by changing age from 33.2 to 34.2 (+1)</p>
<div class="tiny-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(logit_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fl">33.2</span>,    <span class="at">mass_fg =</span> <span class="st">'above-avg'</span>), <span class="at">type =</span> <span class="st">'response'</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(logit_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fl">33.2</span> <span class="sc">+</span><span class="dv">1</span>, <span class="at">mass_fg =</span> <span class="st">'above-avg'</span>), <span class="at">type =</span> <span class="st">'response'</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>p1<span class="sc">-</span>p0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1 
0.01038606 </code></pre>
</div>
</div>
</div>
<div class="small-space">

</div>
<p>and for body mass flag changing from <em>below-avg</em> to <em>above-avg</em>, keeping age constant at the mean of 33.2:</p>
<div class="tiny-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(logit_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fl">33.2</span>, <span class="at">mass_fg =</span> <span class="st">'below-avg'</span>), <span class="at">type =</span> <span class="st">'response'</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(logit_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fl">33.2</span>, <span class="at">mass_fg =</span> <span class="st">'above-avg'</span>), <span class="at">type =</span> <span class="st">'response'</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>p1<span class="sc">-</span>p0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.2253507 </code></pre>
</div>
</div>
</div>
<div class="small-space">

</div>
<p><strong>Interpretation</strong>:</p>
<ul>
<li>For someone with above-average body mass, turning 34 compared to 33 increases the probability of diabetes by 1 percentage point.</li>
<li>For someone aged 33, changing from below-average to above-average body mass increases the probability of diabetes by 24 percentage points.</li>
</ul>
<p><br><br></p>
</section>
<section id="marginal-effects-at-representative-values-mer" class="level3">
<h3 class="anchored" data-anchor-id="marginal-effects-at-representative-values-mer">Marginal Effects at Representative Values (MER)</h3>
<p>We can also examine how marginal effects change across different ages:</p>
<div class="columns">
<div class="column" style="width:58.75%;">
<p><br></p>
<div class="teenytiny-code">
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">comparisons</span>(logit_model, <span class="at">variable =</span> <span class="st">'mass_fg'</span>, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fu">seq</span>(<span class="dv">20</span>, <span class="dv">80</span>, <span class="at">by=</span><span class="dv">10</span>))) <span class="ot">-&gt;</span> c; c</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error    z Pr(&gt;|z|)    S  2.5 % 97.5 % age
    0.179     0.0294 6.10   &lt;0.001 29.8 0.1216  0.237  20
    0.216     0.0332 6.49   &lt;0.001 33.4 0.1504  0.281  30
    0.241     0.0368 6.56   &lt;0.001 34.1 0.1693  0.314  40
    0.250     0.0381 6.55   &lt;0.001 34.1 0.1752  0.325  50
    0.239     0.0378 6.31   &lt;0.001 31.7 0.1645  0.313  60
    0.211     0.0386 5.46   &lt;0.001 24.4 0.1351  0.286  70
    0.173     0.0403 4.31   &lt;0.001 15.9 0.0945  0.252  80

Term: mass_fg
Type:  response 
Comparison: above-avg - below-avg
Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, age, diabetes </code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:2.5%;">

</div><div class="column" style="width:38.75%;">
<div class="tinyer-code">
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>R Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_comparisons</span>(logit_model, <span class="at">variable =</span> <span class="st">'mass_fg'</span>, </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">condition =</span> <span class="fu">list</span>(<span class="st">"age"</span> <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">20</span>, <span class="dv">80</span>, <span class="at">by=</span><span class="dv">10</span>))) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">age =</span> c<span class="sc">$</span>age, <span class="at">est =</span> c<span class="sc">$</span>estimate), <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> est),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">fill =</span> <span class="st">'darkorange'</span>,  <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">'Marginal Effects at Representative Values (MER)'</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">'Risk Difference </span><span class="sc">\n</span><span class="st"> p(above-avg) - p(below-avg)'</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">'Age'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>This analysis suggests that the risk difference peaks around age 50, however, notice that the confidence intervals are relatively broad.</p>
<p>By incorporating marginal effects into our analysis of logistic regression models, we gain a much richer and more intuitive understanding of our data. This approach allows us to communicate complex statistical relationships in terms of probability changes, which are far more accessible to a general audience. Remember, while odds ratios have their place in statistical analysis, marginal effects offer a powerful tool for interpretation and communication in many real-world scenarios.</p>
<p><br><br></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="serigra/Webpage_Quarto" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2025 · Made with <a href="https://www.r-project.org/"><img src="https://www.r-project.org/Rlogo.png" class="img-fluid" alt="R" width="25"></a> and <a href="https://quarto.org/"><img src="https://quarto.org/quarto.png" class="img-fluid" alt="Quarto" width="65"></a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>